openapi: 3.0.0
info:
  title: FlowChart API
  description: API that handles all graph manipulation and presentation
  version: 0.0.1
servers:
  - url: http://localhost:3000/v1
tags:
  - name: Nodes
  - name: Edges
paths:
  /nodes:
    post:
      tags:
        - Nodes
      summary: Add a new node
      description: Add a new node in the structure
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/CreateNodeRequestContent'
      responses:
        '201':
          description: The node was created with success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedNodeResponseContent'

    get:
      tags:
        - Nodes
      summary: List all nodes
      description: List all nodes
      responses:
        200:
          description: All nodes
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NodeSchema'

  /nodes/{uid}:
    get:
      tags:
        - Nodes
      summary: Retrieve one node
      description: Get all information about one node
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            $ref: '#/components/schemas/Uid'
      responses:
        200:
          description: All node information response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/NodeSchema'

  /edges:
    get:
      summary: List all edges
      tags:
        - Edges
      responses:
        200:
          description: Edge list
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EdgeSchema'
    post:
      summary: Create new edge
      tags:
        - Edges
      requestBody:
        content:
          'application/json':
            schema:
              properties:
                startNode:
                  type: object
                  properties:
                    uid:
                      $ref: '#/components/schemas/Uid/properties/uid'
                    name:
                      $ref: '#/components/schemas/NodeSchema/properties/name'
                destinations:
                  type: array
                  items:
                    properties:
                      node:
                        properties:
                          uid:
                            $ref: '#/components/schemas/Uid/properties/uid'
                          name:
                            $ref: '#/components/schemas/NodeSchema/properties/name'
                      edgeProperties:
                        $ref: '#/components/schemas/EdgeSchema'
                        # properties:
                        #   label:
                        #   weight:
                        #     $ref: '#/components/schemas/EdgeSchema/properties/weight'
                        #   tags:
                        #     $ref: '#/components/schemas/EdgeSchema/properties/tags'
      responses:
        201:
          description: Added
          content:
            'application/json':
              schema:
                properties:
                  startNode:
                    type: object
                    properties:
                      uid:
                        $ref: '#/components/schemas/Uid/properties/uid'
                      name:
                        $ref: '#/components/schemas/NodeSchema/properties/name'
                  destinations:
                    type: array
                    items:
                      properties:
                        node:
                          properties:
                            uid:
                              $ref: '#/components/schemas/Uid/properties/uid'
                            name:
                              $ref: '#/components/schemas/NodeSchema/properties/name'
                  edge:
                    properties:
                      uid:
                        $ref: '#/components/schemas/Uid/properties/uid'
                      label:
                        $ref: '#/components/schemas/EdgeLabel/properties/label'
   
  /edges/:uid:
    get:
      tags:
        - Edges
      summary: Retrieve an Edge data
      description: Get all data from an Edge
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            $ref: '#/components/schemas/Uid'

      responses:
        200:
          description: All data from an Edge
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/EdgeSchema'


components:
  schemas:
    Uid:
      properties:
        uid:
          type: string
          description: Unique identifier
          example: 'D6AD7C75-76B6-4D33-9D91-D1DC07046F06'

    CreatedNodeResponseContent:
      properties:
        uid:
          $ref: '#/components/schemas/Uid/properties/uid'
        name:
          type: string
          description: Name of the node
          example: WordPress
        tags:
          type: array
          items:
            type: string
          example:
            - internal
            - exploitable
            - vulnerable
            - web
            - network

    CreateNodeRequestContent:
      $ref: '#/components/schemas/NodeSchema'
      # properties:
      #   name:
      #     type: string
      #     description: Name of the node
      #     example: WordPress
      #   port:
      #     type: number
      #     description: Port that the service represented by the node is running
      #     example: 80
      #   tags:
      #     description: List of tags that can help filtering
      #     type: array
      #     items:
      #       type: string
      #     example:
      #       - internal
      #       - exploitable
      #       - vulnerable
      #       - web
      #       - network
      #   metadata:
      #     properties:
      #       command:
      #         type: string
      #         description: Executed command. Useful when the node is a "command" node
      #         example: 'nmap -sC -sV -oA nmap/initial vulnerable-server.com'

    EdgeSchema:
      properties:
        uid:
          $ref: '#/components/schemas/Uid/properties/uid'
        label:
          $ref: '#/components/schemas/EdgeLabel/properties/label'
        weight:
          type: number
          description: Weight of the edge
          example: 34.44
        tags:
          type: array
          items:
            properties:
              key:
                type: string
                description: Key of the tag
                example: URL
              value:
                type: string
                description: Value of the tag
                example: http://example.com/vulnerable/contact/form

    EdgeLabel:
      properties:
        label:
          type: string
          description: Label of the edge
          example: Cross Site Script (XSS)

    NodeSchema:
      properties:
        uid:
          type: string
          description: Unique identifier of the node
          example: 'D6AD7C75-76B6-4D33-9D91-D1DC07046F06'
        name:
          type: string
          description: Name of the node
          example: WordPress
        edges:
          type: array
          items:
            properties:
              goFrom:
                description: List of edges uid that go from this node to another place
                type: array
                items:
                  $ref: '#/components/schemas/EdgeSchema'
              comeTo:
                description: List of edges uid that come to this node from somewhere
                type: array
                items:
                  $ref: '#/components/schemas/EdgeSchema'
        port:
          type: number
          description: Port that the service represented by the node is running
          example: 80
        tags:
          type: array
          items:
            type: string
          example:
            - internal
            - exploitable
            - vulnerable
            - web
            - network
        metadata:
          properties:
            command:
              type: string
              description: Executed command. Useful when the node is a "command" node
              example: 'nmap -sC -sV -oA nmap/initial vulnerable-server.com'
